# Generated by Django 2.2.9 on 2022-08-10 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20220810_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(None), related_name='no_group', to='posts.Group'),
        ),
    ]
