# Generated by Django 2.2.6 on 2022-08-26 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20220811_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.TextField(max_length=300, null=True),
        ),
    ]
