# Generated by Django 2.2.6 on 2022-08-26 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20220826_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.TextField(default='Описание группы', max_length=300),
            preserve_default=False,
        ),
    ]
