# Generated by Django 2.2.16 on 2022-09-22 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0026_auto_20220922_2136'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created']},
        ),
    ]
